---
- name: Cloning faad2 project from GitHub.
  git:
    repo: https://github.com/mecke/faad2.git
    dest: /usr/local/src/faad2
    version: b837128d2afef284e3fec79989e4d340b1e68ab6
    force: true
  become: true

- name: Validate installed faad2.
  stat: 
    path: /usr/local/lib/libfaad.so
  register: faad2_installed

- name: Build faad2.
  shell: '{{ item }}'
  args:
    chdir: /usr/local/src/faad2
  become: true
  when: not faad2_installed.stat.exists
  with_items:
    - ./configure
    - make

- name: Install builded faad2.
  shell: make install
  when: not faad2_installed.stat.exists
  become: true
  args:
    chdir: /usr/local/src/faad2
