---
- name: Detect installed libmad.
  stat: 
    path: /usr/local/lib/libmad.so
  register: libmad_installed

- name: Detect downloaded libmad.
  stat: 
    path: /vagrant/.tmp/libmad-0.15.0b.tar.gz
  register: libmad_downloaded

- name: Download libmad.
  get_url:
    url: ftp://ftp.mars.org/pub/mpeg/libmad-0.15.0b.tar.gz
    dest: /vagrant/.tmp/libmad-0.15.0b.tar.gz
  when: libmad_downloaded is defined and
        not libmad_downloaded.stat.exists

- name: Deploy libmad.
  shell: tar zxf /vagrant/.tmp/libmad-0.15.0b.tar.gz
  args:
    chdir: /usr/local/src/
  become: true
  when: not libmad_installed.stat.exists

- name: Remove -fforce-mem build option.
  lineinfile:
    dest: '/usr/local/src/libmad-0.15.0b/{{ item }}'
    regexp: '-fforce-mem'
    line: ''
  when: not libmad_installed.stat.exists
  become: true
  with_items:
  - configure
  - configure.ac

- name: Build libmad.
  shell: '{{ item }}'
  when: not libmad_installed.stat.exists
  args:
    chdir: /usr/local/src/libmad-0.15.0b
  become: true
  with_items:
    - ./configure
    - make

- name: Install builded libmad.
  shell: make install
  when: not libmad_installed.stat.exists
  become: true
  args:
    chdir: /usr/local/src/libmad-0.15.0b
