---
- name: Cloning FFmpeg project from GitHub.
  git:
    repo: https://github.com/FFmpeg/FFmpeg.git
    dest: /usr/local/src/FFmpeg
    version: 4853b5538f416ba4d519244fde8c14f2ff75e07b
  become: true

- name: Validate necessity of build FFmpeg.
  stat: 
    path: /usr/local/bin/ffmpeg
  register: ffmpeg_installed

- name: Build FFmpeg.
  shell: '{{ item }}'
  when: not ffmpeg_installed.stat.exists
  become: true
  args:
    chdir: /usr/local/src/FFmpeg
  with_items:
    - ./configure --enable-pic --enable-shared --enable-stripping --enable-gpl
    - make

- name: Install built FFmpeg binaries.
  shell: make install
  when: not ffmpeg_installed.stat.exists
  become: true
  args:
    chdir: /usr/local/src/FFmpeg
