---
- name: Detect deployed FFmpeg.
  stat: 
    path: /usr/local/src/FFmpeg-n1.2
  register: ffmpeg_deployed

- name: Detect downloaded FFmpeg.
  stat: 
    path: /vagrant/.tmp/n1.2.tar.gz
  register: ffmpeg_downloaded
  when: not ffmpeg_deployed.stat.exists

- name: Download FFmpeg.
  get_url:
    url: https://github.com/FFmpeg/FFmpeg/archive/n1.2.tar.gz
    dest: /vagrant/.tmp/n1.2.tar.gz
  when: ffmpeg_downloaded is defined and
        not ffmpeg_downloaded.stat.exists

- name: Deploy FFmpeg.
  shell: tar zxf /vagrant/.tmp/n1.2.tar.gz
  args:
    chdir: /usr/local/src/
  when: not ffmpeg_deployed.stat.exists

- name: Validate installed ffmpeg.
  stat: 
    path: /usr/local/bin/ffmpeg
  register: ffmpeg_installed

- name: Validate build necessary.
  stat:
    path: /usr/local/src/FFmpeg-n1.2/ffmpeg
  register: ffmpeg_builded
  when: not ffmpeg_installed.stat.exists

- name: Build ffmpeg.
  shell: '{{ item }}'
  when: ffmpeg_builded is defined and
        not ffmpeg_builded.stat.exists
  args:
    chdir: /usr/local/src/FFmpeg-n1.2
  become: true
  with_items:
    - ./configure --enable-pic --enable-shared --enable-stripping --enable-gpl
    - make

- name: Install builded ffmpeg.
  shell: make install
  when: not ffmpeg_installed.stat.exists
  become: true
  args:
    chdir: /usr/local/src/FFmpeg-n1.2
