---
- name: Detect built FFmpeg.
  stat: 
    path: ~/workspace/lib_android/avbuild/sdk-android-x86
  register: ffmpeg_built

- name: Detect downloaded FFmpeg.
  stat: 
    path: /vagrant/.tmp/n1.2.11.tar.gz
  register: ffmpeg_downloaded
  when: not ffmpeg_built.stat.exists

- name: Download FFmpeg.
  get_url:
    url: https://github.com/FFmpeg/FFmpeg/archive/n1.2.11.tar.gz
    dest: /vagrant/.tmp/n1.2.11.tar.gz
  when: ffmpeg_downloaded is defined and
        not ffmpeg_downloaded.stat.exists

- name: Deploy FFmpeg.
  shell: tar zxf /vagrant/.tmp/n1.2.11.tar.gz
  args:
    chdir: ~/workspace/lib_android/
  when: not ffmpeg_built.stat.exists

- name: Deploy build_ffmpeg.
  shell: tar Jxf /vagrant/src/build_ffmpeg.tar.xz
  args:
    chdir: ~/workspace/lib_android/
  when: not ffmpeg_built.stat.exists

- name: Set environment var ANDROID_NDK.
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export\sANDROID_NDK =\$\{ANDROID_NDK_HOME\}'
    line: 'export ANDROID_NDK=${ANDROID_NDK_HOME}'

- name: Build FFmpeg.
  shell: ./build_ffmpeg.sh android
  args:
    chdir: ~/workspace/lib_android/
  when: not ffmpeg_built.stat.exists
