---
- name: Rebuild dependencies caches.
  shell: /sbin/ldconfig
  become: yes
  changed_when: false

- name: Cleanup btrfs snapshot.
  shell: snapper delete 2-100000
  become: yes
  ignore_errors: true
  changed_when: false
